"""empty message

Revision ID: cf8fd019aa4b
Revises: a1551b1b3b2a
Create Date: 2022-07-15 20:50:26.599879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8fd019aa4b'
down_revision = 'a1551b1b3b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
